import type { Metadata } from "next";
import { Inter,Roboto } from "next/font/google";
import "./globals.css";
import AppProvider from "@/components/providers";

const roboto = Roboto({subsets:["greek"],weight:['100','400','500'],variable:'--font-roboto'});

export const metadata: Metadata = {
  title: "Esi's Kitchen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
