import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import NavBar from "@/components/customs/navbar";

const poppins = localFont({
  src: [
    {

      path: './fonts/Poppins-Black.ttf',
      weight: '700',
      style: 'normal',

    },
    {
      path: './fonts/Poppins-Bold.ttf',
      weight: '400',
      style: 'normal'
    },
    {
      path: './fonts/Poppins-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/Poppins-Medium.ttf',
      weight: '400',
      style: 'italic',
    },
  ],
})

export const metadata: Metadata = {
  title: "Esi's Kitchen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={`${poppins.className} antialiased`}
      >
        <NavBar/>
        <main>
        {children}
        </main>
      </body>
    </html>
  );
}
